[global]
domainNumber              42
network_transport         UDPv4
delay_mechanism           E2E
time_stamping             hardware
clock_servo               pi
delay_filter              moving_median
delay_filter_length       10
tx_timestamp_timeout      100
logging_level             6
summary_interval          0
logSyncInterval           -3
logAnnounceInterval       0
logMinDelayReqInterval    0
priority1                 100
priority2                 100
twoStepFlag               1
# Never touch CLOCK_REALTIME; only the NIC PHC is steered.
[enp196s0f1np1]
